### ISSUE TITLE
Add notification sidebar

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/bedel#12]
I'm currently in the progress of adding a notification sidebar.
It will get notification from the server and display them. Socket.io will be used for active notifications.

Feature checklist:

- [x] :art: Add socket.io backend
- [x] :art: Add notication validation
- [x] :lipstick: Add displaying of notifications with body and app from.
- [x] :lipstick: Add direct web browser notifications with push.js
- [x] :lipstick: Add custom badge support (url only, base64 in v2.0.0 (#13))
- [x] :lipstick: Add dismiss button
- [x] :lipstick: Add a 'dismiss all button'
- [x] :lipstick: Add usage of custom react/HTML components as notification body (must be rendered to string for react)
- [x] :lipstick: Add tabs for notifications and tasks (will now do separately)
- [x] :lipstick: Add sliding open
