### ISSUE TITLE
Add tasks sidebar (CHECKLIST)

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/bedel#14]
This is a feature tracker for the task sidebar. Its continues on from #12.

**Aim:** To provide an easy to use view for showing running tasks

**Pull Request:** #23

Checklist:

- [x] :lipstick: Add time received to notifications
- [x] :lipstick: Use tabs for sidebar
- [x] :lipstick: Make one of the tabs for notifications and the other for tasks
- [x] :art: Add tasks backend
- [x] :lipstick: Decide on a design for a single task
- [x] :art: Implement the redux reducers and actions for tasks
- [x] :lipstick: Create the actual tabs component
- [x] :art: :lipstick: Add mapping of tasks for status, progress (bar), info and app.
- [x] :lipstick: Add buttons to:
      - [x] cancel
      - [x] ~~pause/continue~~ Very hard for a developer to pause the execution of code.
      - [x] 'view more'
- [x] :lipstick: Add a 'no tasks/notifications' message
- [x] :lipstick: Add tasks & notifications unread/not viewed counter
- [x] :art: Add notifications ~~+ tasks~~ (not needed, as socket.io emits everything already emitted) caching into database
- [x] ~~:lipstick: Add sliding out of cancelled or dismissed tasks/notifications (will decide using feedback)~~ (Decided against due to upcoming ux redo)

**Comment by Gum-Joe** [comment]
All done here.
