### ISSUE TITLE
Increase responsiveness of components

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/bedel#15]
**Aim:** This is the tracker for increasing the responsiveness of components
Checklist:

- [ ]  :lipstick: Check what doesn't appear on several mobile devices + run thinck with google tests
- [ ] :bug: :ambulance: Find a way to fix any issues found
- [ ] :lipstick: Use sauce labs or browser stack to test on multiple platforms
- [ ] :bug: :ambulance: Find a way to fix any issues found
