### ISSUE TITLE
Fix code climate compliants

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/bedel#16]
This is a list of issues that are from linters on code climate.

**Aim:** To get rating 3.9 to 4 on codeclimate

**List:**
##### B Rating:
- [x] #34 client/base/reducers/Counter.js

##### C Rating:
- [x] #32 webpack.dev.js
- [x] #31 webpack.config.js
- [x] #30 app/util/logger.js
- [x] #29 client/base/components/navbar/sidebar.jsx
- [x] #28 app/cli/index.js
- [x] #27 client/base/reducers/Tasks.js
- [x] #26 client/base/components/navbar/item.jsx

##### D Rating:
- [x] #25 client/base/components/sidebar.jsx
- [x] #24 app/helpers/api.js

**Comment by Gum-Joe** [comment]
All were improved on a config change
