### ISSUE TITLE
Redo ui

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/bedel#36]
It is time to redo the ui.
Tools:

- Semantic UI
- Bootstrap
- React
- Admin LTE (https://almsaeedstudio.com/preview) as inspiration

Checklist:

- [ ] Setup Semantic UI
- [ ] Create base UI (Sidebar, navbar)
     - [ ] Add react-router
     - [ ] Add sidebar
     - [ ] Add top navbar
     - [ ] Add notifications and tasks view
- [ ] Create widgets and have a drag-drop system
- [ ] Add apps api
- [ ] Add screen for apps
- [ ] Add apps:
     - [ ] Settings
     - [ ] Messaging
